apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-claim0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      io.polaris.service: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        io.polaris.service: elasticsearch
    spec:
      nodeSelector:
        nodelevel: instable
      containers:
      - env:
        - name: discovery.type
          value: single-node
        image: elasticsearch:6.8.4
        name: elasticsearch
        ports:
        - containerPort: 9200
        - containerPort: 9300
        resources:
          requests:
            cpu: "0.5"
            memory: 200Mi
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9200
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 9200
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elasticsearch-claim0
      restartPolicy: Always
      dnsPolicy: ClusterFirst
      volumes:
      - name: elasticsearch-claim0
        persistentVolumeClaim:
          claimName: elasticsearch-claim0
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
spec:
  ports:
  - name: "tcp"
    port: 9200
    targetPort: 9200
  selector:
    io.polaris.service: elasticsearch
