version: '3.7'

services:
    mysql:
        image: mysql:8.0
        restart: always
        ports:
            - "3306:3306"
        volumes:
            - ./data:/var/lib/mysql
            - ./conf:/etc/mysql/conf.d
            - /etc/localtime:/etc/localtime
        environment:
            - MYSQL_ROOT_PASSWORD=shangHai@123
