apiVersion: v1
kind: Service
metadata:
  name: dingtalk
spec:
  ports:
  - name: "tcp"
    port: 8060
    targetPort: 8060
  selector:
    io.polaris.service: dingtalk
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dingtalk
  labels:
    k8s-app: dingtalk
data:
  config.yml: |-
    targets:
      webhook1:
        url: https://oapi.dingtalk.com/robot/send?access_token=ea9ef8e4104f77de6eeaa822c7d721950b95c250bdc9b946c027973ea255403f
        secret: SEC0c0aab43c4b3e5df9ee0d4b618480cbcc3f34163409904b150e83c481b35c689
      webhook2:
        url: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxx
      webhook_legacy:
        url: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxx
        message:
          title: '{{ template "legacy.title" . }}'
          text: '{{ template "legacy.content" . }}'
      webhook_mention_all:
        url: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxx
        mention:
          all: true
      webhook_mention_users:
        url: https://oapi.dingtalk.com/robot/send?access_token=xxxxxxxxxxxx
        mention:
          mobiles: ['156xxxx8827', '189xxxx8325']

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dingtalk
spec:
  progressDeadlineSeconds: 600
  selector:
    matchLabels:
      io.polaris.service: dingtalk
  replicas: 1
  template:
    metadata:
      labels:
        io.polaris.service: dingtalk
    spec:
      containers:
      - image: timonwong/prometheus-webhook-dingtalk:latest
        name: dingtalk
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "0.05"
            memory: 50Mi
        command: ["/bin/prometheus-webhook-dingtalk","--config.file=/etc/prometheus-webhook-dingtalk/configmap/config.yml"]
        livenessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 8060
          initialDelaySeconds: 300
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        readinessProbe:
          failureThreshold: 3
          tcpSocket:
            port: 8060
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 5
        volumeMounts:
        - name: dingtalk
          mountPath: /etc/prometheus-webhook-dingtalk/configmap
      volumes:
        - name: dingtalk
          configMap:
            name: dingtalk
      restartPolicy: Always
      dnsPolicy: ClusterFirst
