#!/bin/bash
echo -e "\e[32m-------ck1-------"'\033[32m\033[0m'
$*
echo -e "\n\e[32m-------ck2-------"'\033[32m\033[0m'
ssh ck2 "cd $PWD && $*"
echo -e "\n\e[32m-------ck3-------"'\033[32m\033[0m'
ssh ck3 "cd $PWD && $*"
