apiVersion: v1
generated: "2019-12-11T02:33:08.145259003+08:00"
repositories:
- caFile: ""
  cache: /root/.helm/repository/cache/stable-index.yaml
  certFile: ""
  keyFile: ""
  name: stable
  password: ""
  url: https://kubernetes.oss-cn-hangzhou.aliyuncs.com/charts
  username: ""
- caFile: ""
  cache: /root/.helm/repository/cache/local-index.yaml
  certFile: ""
  keyFile: ""
  name: local
  password: ""
  url: http://127.0.0.1:8879/charts
  username: ""
- caFile: ""
  cache: /root/.helm/repository/cache/elastic-index.yaml
  certFile: ""
  keyFile: ""
  name: elastic
  password: ""
  url: https://helm.elastic.co
  username: ""
- caFile: ""
  cache: /root/.helm/repository/cache/microsoft-index.yaml
  certFile: ""
  keyFile: ""
  name: microsoft
  password: ""
  url: http://mirror.azure.cn/kubernetes/charts
  username: ""
- caFile: ""
  cache: /root/.helm/repository/cache/aliyun-index.yaml
  certFile: ""
  keyFile: ""
  name: aliyun
  password: ""
  url: https://apphub.aliyuncs.com
  username: ""
